name = "guardian-dns-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"
workers_dev = true

[[kv_namespaces]]
binding = "DNS_CACHE"
id = "5e43bae88c574980897cd06c21435fe5"

[ai]
binding = "AI"
